#!/bin/bash

selections=(
#	"N,nF:RT:th_y_low"
#	"N,nF:RT:th_y_high"
#	"nN,F:RT"
	"nN,nF:RT"
	"nN,nF:LB"
)

#----------------------------------------------------------------------------------------------------

function ProcessOne()
{
	echo $dir

	cp "make_plots.asy" "$dir"
	cd "$dir" || return 1

	asy "make_plots.asy"

	cd - &> /dev/null
}

#----------------------------------------------------------------------------------------------------

for dir in ${selections[*]}
do
	ProcessOne
done
